import Head from "next/head";
import Navbar from "./components/Navbar";
import Test from "./components/Test";
import Result from "./components/Result";
import { useState } from "react";
export default function Home() {
const [start, setStart] = useState(false)
const [end, setEnd] = useState(false)

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar></Navbar>
        <div className="main-screen">
        {start ? <Test/>: <div className="w-full h-screen flex justify-center items-center">
<button onClick={()=> setStart(true)}>Start</button>
          </div>}
         
        </div>
      </main>
    </>
  );
}
